from dataclasses import dataclass
from pyspark.sql.types import (
    BooleanType,
    DateType,
    DecimalType,
    IntegerType,
    LongType,
    StringType,
    TimestampType,
)


@dataclass(frozen=True)
class TableSpec:
    columns: list[tuple[str, object]]
    primary_keys: list[str]


# Mirrors database/init_schema.sql. Silver keeps the operational table columns
# plus event_date as the Delta partition column.
TABLE_SPECS = {
    "platforms": TableSpec(
        [
            ("platform_id", IntegerType()),
            ("platform_code", StringType()),
            ("platform_name", StringType()),
            ("base_url", StringType()),
            ("is_active", BooleanType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["platform_id"],
    ),
    "sellers": TableSpec(
        [
            ("seller_id", LongType()),
            ("platform_id", IntegerType()),
            ("platform_seller_id", StringType()),
            ("seller_name", StringType()),
            ("city", StringType()),
            ("province", StringType()),
            ("follower_count", IntegerType()),
            ("is_official_store", BooleanType()),
            ("status", StringType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["seller_id"],
    ),
    "customers": TableSpec(
        [
            ("customer_id", LongType()),
            ("platform_id", IntegerType()),
            ("platform_customer_id", StringType()),
            ("full_name", StringType()),
            ("email", StringType()),
            ("phone_number", StringType()),
            ("gender", StringType()),
            ("date_of_birth", DateType()),
            ("status", StringType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["customer_id"],
    ),
    "customer_addresses": TableSpec(
        [
            ("address_id", LongType()),
            ("customer_id", LongType()),
            ("recipient_name", StringType()),
            ("phone_number", StringType()),
            ("address_line", StringType()),
            ("ward", StringType()),
            ("district", StringType()),
            ("city", StringType()),
            ("province", StringType()),
            ("country", StringType()),
            ("postal_code", StringType()),
            ("is_default", BooleanType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["address_id"],
    ),
    "categories": TableSpec(
        [
            ("category_id", LongType()),
            ("platform_id", IntegerType()),
            ("platform_category_id", StringType()),
            ("parent_category_id", LongType()),
            ("category_name", StringType()),
            ("is_active", BooleanType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["category_id"],
    ),
    "brands": TableSpec(
        [
            ("brand_id", LongType()),
            ("platform_id", IntegerType()),
            ("platform_brand_id", StringType()),
            ("brand_name", StringType()),
            ("country", StringType()),
            ("is_official", BooleanType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["brand_id"],
    ),
    "products": TableSpec(
        [
            ("product_id", LongType()),
            ("platform_product_id", StringType()),
            ("seller_id", LongType()),
            ("category_id", LongType()),
            ("brand_id", LongType()),
            ("product_name", StringType()),
            ("description", StringType()),
            ("status", StringType()),
            ("is_authentic", BooleanType()),
            ("published_at", TimestampType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["product_id"],
    ),
    "product_variants": TableSpec(
        [
            ("variant_id", LongType()),
            ("product_id", LongType()),
            ("platform_variant_id", StringType()),
            ("sku", StringType()),
            ("variant_name", StringType()),
            ("original_price", DecimalType(18, 2)),
            ("sale_price", DecimalType(18, 2)),
            ("weight_gram", IntegerType()),
            ("status", StringType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["variant_id"],
    ),
    "product_inventory": TableSpec(
        [
            ("inventory_id", LongType()),
            ("variant_id", LongType()),
            ("warehouse_code", StringType()),
            ("quantity_on_hand", IntegerType()),
            ("quantity_reserved", IntegerType()),
            ("low_stock_threshold", IntegerType()),
            ("updated_at", TimestampType()),
        ],
        ["inventory_id"],
    ),
    "inventory_movements": TableSpec(
        [
            ("movement_id", LongType()),
            ("inventory_id", LongType()),
            ("movement_type", StringType()),
            ("quantity_delta", IntegerType()),
            ("reference_type", StringType()),
            ("reference_id", StringType()),
            ("reason", StringType()),
            ("occurred_at", TimestampType()),
        ],
        ["movement_id"],
    ),
    "vouchers": TableSpec(
        [
            ("voucher_id", LongType()),
            ("platform_id", IntegerType()),
            ("seller_id", LongType()),
            ("voucher_code", StringType()),
            ("voucher_name", StringType()),
            ("discount_type", StringType()),
            ("discount_value", DecimalType(18, 2)),
            ("max_discount_amount", DecimalType(18, 2)),
            ("min_order_amount", DecimalType(18, 2)),
            ("usage_limit", IntegerType()),
            ("starts_at", TimestampType()),
            ("ends_at", TimestampType()),
            ("status", StringType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["voucher_id"],
    ),
    "carts": TableSpec(
        [
            ("cart_id", LongType()),
            ("customer_id", LongType()),
            ("status", StringType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["cart_id"],
    ),
    "cart_items": TableSpec(
        [
            ("cart_item_id", LongType()),
            ("cart_id", LongType()),
            ("variant_id", LongType()),
            ("quantity", IntegerType()),
            ("unit_price", DecimalType(18, 2)),
            ("added_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["cart_item_id"],
    ),
    "orders": TableSpec(
        [
            ("order_id", LongType()),
            ("platform_order_id", StringType()),
            ("customer_id", LongType()),
            ("seller_id", LongType()),
            ("shipping_address_id", LongType()),
            ("voucher_id", LongType()),
            ("order_status", StringType()),
            ("subtotal_amount", DecimalType(18, 2)),
            ("shipping_fee", DecimalType(18, 2)),
            ("discount_amount", DecimalType(18, 2)),
            ("total_amount", DecimalType(18, 2)),
            ("ordered_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["order_id"],
    ),
    "order_items": TableSpec(
        [
            ("order_item_id", LongType()),
            ("order_id", LongType()),
            ("variant_id", LongType()),
            ("quantity", IntegerType()),
            ("unit_price", DecimalType(18, 2)),
            ("discount_amount", DecimalType(18, 2)),
        ],
        ["order_item_id"],
    ),
    "payments": TableSpec(
        [
            ("payment_id", LongType()),
            ("order_id", LongType()),
            ("payment_method", StringType()),
            ("provider", StringType()),
            ("amount", DecimalType(18, 2)),
            ("status", StringType()),
            ("paid_at", TimestampType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["payment_id"],
    ),
    "shipments": TableSpec(
        [
            ("shipment_id", LongType()),
            ("order_id", LongType()),
            ("carrier_name", StringType()),
            ("tracking_number", StringType()),
            ("shipping_method", StringType()),
            ("status", StringType()),
            ("shipped_at", TimestampType()),
            ("estimated_delivery_at", TimestampType()),
            ("delivered_at", TimestampType()),
            ("created_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["shipment_id"],
    ),
    "product_reviews": TableSpec(
        [
            ("review_id", LongType()),
            ("platform_review_id", StringType()),
            ("product_id", LongType()),
            ("order_item_id", LongType()),
            ("customer_id", LongType()),
            ("rating", IntegerType()),
            ("title", StringType()),
            ("content", StringType()),
            ("delivery_rating", IntegerType()),
            ("seller_rating", IntegerType()),
            ("helpful_count", IntegerType()),
            ("status", StringType()),
            ("reviewed_at", TimestampType()),
            ("updated_at", TimestampType()),
        ],
        ["review_id"],
    ),
    "events": TableSpec(
        [
            ("event_id", LongType()),
            ("platform_event_id", StringType()),
            ("customer_id", LongType()),
            ("product_id", LongType()),
            ("variant_id", LongType()),
            ("cart_item_id", LongType()),
            ("order_item_id", LongType()),
            ("event_type", StringType()),
            ("created_at", TimestampType()),
        ],
        ["event_id"],
    ),
}
